# version: "3.9"

services:
  db:
    image: postgres:16.2
    container_name: 'bookingdb'
    restart: always
    environment:
      - POSTGRES_DB=bookingdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=dangerous
    ports:
      - 5432:5432
    networks:
        - backend

  redis:
    image: redis:latest
    container_name: rediscache
    ports:
      - "6379:6379"
    restart: always
    networks:
        - backend
  
  booking-service:
    image: booking-service:latest
    container_name: 'booking-service'
    build:
      context: . 
    ports:
      - 8080:8080
      - 5005:5005
    volumes:
      - ./src/main/resources/application.yml:/app/config/application.yml
      - ./src/main/resources/application-local.yml:/app/config/application-local.yml
    environment:
      - SPRING_CONFIG_LOCATION=file:/app/config/application.yml
    networks:
        - backend
    depends_on:
      - db

networks:
  backend:
    driver: bridge
  
