# version: "3.9"

services:
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: dangerous
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
       - "5050:80"
    networks:
        - backend
  db:
    # image: postgres:16.2-alpine3.19
    image: postgres:16.2
    container_name: 'bookingdb'
    restart: always
    environment:
      - POSTGRES_DB=bookingdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=dangerous
    # volumes:
    #   - ./src/main/resources/V1__initial_setup.sql:/docker-entrypoint-initdb.d/V1__initial_setup.sql
    ports:
      - 5432:5432
    networks:
        - backend
  
  booking-service:
    image: booking-service:latest
    container_name: 'booking-service'
    build:
      context: . 
    ports:
      - 8080:8080
      - 5005:5005
    volumes:
      - ./src/main/resources/application.yml:/app/config/application.yml
      - ./src/main/resources/application-local.yml:/app/config/application-local.yml
    environment:
      - SPRING_CONFIG_LOCATION=file:/app/config/application.yml
    networks:
        - backend
    depends_on:
      - db

networks:
  backend:
    driver: bridge
  
