spring:
  data:
    redis:
        host: rediscache
        port: 6379
        timeout: 60000

  datasource:
    url: jdbc:postgresql://bookingdb:5432/bookingdb
    username: admin
    password: dangerous
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    # properties:
    #   hibernate:
    #     format_sql: true

logging:
  level:
    root: info
    # org.hibernate.SQL: DEBUG
    # org.hibernate.orm.jdbc.bind: TRACE
